### ISSUE TITLE
Write a case example on jupyter notebook

### ISSUE THREAD

**Issue by dhuy228** [dhuy228/augmented-volumetric-image-generator#1]

**Comment by dhuy228** [comment]
Raised by https://github.com/keras-team/keras/issues/2939#issuecomment-543396040

**Comment by Mcitrin** [comment]
really my goal is just to load the image data generator with my 3d patches and make augmented versions that are randomly rotated about the x,y, and z axis


from Unet3D.helper import save_nii, load_patches
import Unet3D.customImageGenerator as cig

_*** this is function i defined in your image generator as i wasn't sure how to properly call random rotation as a pre conditioning function***_
def random_rotation2(x):
    return random_rotation(x, 30, 0,1,2)

imgs, labels = load_patches("input_directory", 32)

imgs = imgs.reshape(imgs.shape[0],imgs.shape[1],imgs.shape[2],imgs.shape[3],1)
labels = labels .reshape(labels .shape[0],labels .shape[1],labels .shape[2],labels .shape[3],1)

datagen = cig.customImageDataGenerator(preprocessing_function=cig.random_rotation2)

for X_batch, y_batch in datagen2.flow(imgs_9, labels_9, batch_size=9):
--# create a grid of 3x3 images
--print(X_batch.shape)
--cnt = 0
--for i in X_batch:
------ save_nii(i.reshape(32,32,32),"./" + str(cnt) + "img.nii")   
------ cnt = cnt + 1   
--cnt = 0
--for i in y_batch:
------save_nii(i.reshape(32,32,32),"./" + str(cnt) + "label.nii")   
 ----- cnt = cnt + 1  
 break

**Comment by dhuy228** [comment]
@Mcitrin The data generator current only rotates based on one fixed axis. I believe it is Z axis which is fixed.

You can easily make it rotate based on other axes by flipping the input data before putting it in the data generator.
